# Change these first
owner: theatl-social # Your GitHub organization or username, where this repository lives
repo: theatl-social-status # The name of this repository

sites:
  - name: theATL.social Main Site
    url: https://theATL.social
  - name: theATL.social Public API
    url: https://theatl.social/api/v1/timelines/public?local=true&only_media=false
  - name: about.theATL.social 
    url: https://about.theATL.social

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.theATL.social
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "status.theATL.social is provided by **Upptime**, the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Status updates are continuously updated. For questions or comments, refer to the generated incident, or email [admin@theatl.social](mailto:admin@theatl.social)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
